package com.appentus.shedistrict.network

class AppConstant {
    companion object {
        var BaseUrl = "http://52.14.206.24/api/Api_v1/"
        var ImageUrl = "http://52.14.206.24/"
        var unplaceImage ="unsplash"
        var unplaceImageSearch ="unplaceImageSearch"
        var Success = "success"
        var Failed =  "failed"
        var device_type = "device_type"
        var deviceTypeValue = 1
        var device_token = "device_token"
        var deviceTokenValue = "fcm"
        var userInfo = "userInfo"
        var userSession = "userSession"
        var user_signup = "user_signup"
        var she_rules = "she_rules"
        var create_profile = "create_profile"
        var add_photos = "add_photos"
        var user_login = "user_login"
        var post_category = "post_category"
        var add_announcement = "add_announcement"
        var social = "social"
        var social_login = "social_login"
        var get_preference = "get_preference"
        var get_friend_list ="get_friend_list"
        var get_meet_content = "get_meet_content"
        var get_privacy_terms = "get_privacy_terms"
        var send_message = "send_message"
        var get_message = "get_message"
        var user_report = "user_report"
        var chat_list = "chat_list"
        var get_user_profile = "get_user_profile"
        var schedule_meeting = "schedule_meeting"
        var get_events = "get_events"
        var get_hobbies = "get_hobbies"
        var get_interest = "get_interest"
        var update_event_status = "update_event_status"
        var app_faq = "app_faq"
        var app_content = "app_content"
        var update_user_name = "update_user_name"
        var my_announcements = "my_announcements"
        var get_announcements = "get_announcements"
        var announcement_delete = "announcement_delete"
        var notification = "update_notification_setting"
        var  Update_message_setting = "update_message_setting"
        var  Update_profile_setting = "update_profile_setting"
        var  User_active_deactive = "user_active_deactive"
        var  Block_user_list = "get_block_user"
        var  User_unblock = "user_unblock"
        var  User_by_preference = "user_by_preference"
        var  Like = "do_like"
        var  DisLike = "dis_like"
        var  Describe_me_data = "describe_data"
        var  personal_info_data = "personal_info_data"
        var  update_password = "update_password"
        var  update_user_profile = "update_user_profile"
        var  replace_or_remove = "replace_or_remove"
        var  update_photos = "update_photos"
        var  get_security_question = "get_security_question"
        var  get_user_by_email = "get_user_by_email"
        var  forget_password = "forget_password"
        var  get_plan = "get_plan"
        var  get_viewers = "get_viewers"
        var  get_boosts_plan = "get_boosts_plan"
        var  active_deactive = "active_deactive"
        var  add_friend = "add_friend"
        var  remove_friend = "remove_friend"
        var  get_she_friends = "get_she_friends"
        var  active_she_protect = "active_she_protect"
        var  purchase_plan = "purchase_plan"
        var  user_block = "user_block"
        var  update_online_offline = "update_online_offline"
        var  boosts_users = "boosts_users"
        var  get_my_plan = "get_my_plan"
        var  cancel_plan = "cancel_plan"
        var  send_meet_request = "send_meet_request"
        var  status_meet_request = "status_meet_request"
        var  boosts_again = "boosts_again"

    }

    object NotificationEventFilter {
        var invitation = "invitation"
        var invitation_send = "invitation_send"
        var invitation_accept = "invitation_accept"
        var invitation_deny = "invitation_deny"
        var newMessage = "newMessage"
        var verify = "verify"
        var unverify = "unverify"
        var accept_meet ="accept_meet"

    }
}